### ISSUE TITLE
Discussion: Introduce stricter error handling than Ramda

### ISSUE THREAD

**Issue by selfrefactor** [selfrefactor/rambda#556]
This issue will stay open until February 2021, when it will either be applied or ignored. The idea is to have time to collect your opinion on the matter.

I have a problem with such code:

```
export function map(fn, list){
    if (list === undefined) return []
}
```

One issue is that this allows silent errors, which can be confusing.
Second issue is that in Typescript, one will never be able to pass `undefined` as list. This means that any code that depends on this fallback, will require Typescript users to do additional magic.

But this exempt from `Rambda.map` is there, because Rambda aim to be compatible with Ramda, which to some extent includes the error handling. Here is where things get interesting - it is not possible to have full compatibility in this regard, without coping the logic of Ramda methods. So maybe, we can use this downside to introduce stricter error handling. In other words, if the method's arguments are not from expected types, then Rambda will throw an error. This will change the above code to:

```
export function map(fn, list){
    if (!['Object','Array'].includes(type(list)){
       throw new Error('`list` is neither list not an object')
   }
   if(typeof fn !== 'function'){
      throw new Error('`fn` is not a function')
   }

}
```

The additional checks may slow down performance, so this change will be compared with benchmarks to assure that speed penalty is neglectable. If there is a penalty, then the code could simplyfied to:

```
export function map(fn, list){
    if (!list || !fn){
       throw new Error('falsy values are not accepted')
   }

}
```

The question is not that much about how error handling is applied, but to confirm that we, as users of Rambda, find such fallback as bad practice.

I will welcome any insights on the matter, as this is major change(will produce a major bump) and feedback is crucial.

**Comment by VoidNoire** [comment]
Personally I'd prefer better and stricter error handling over 1:1 compatibility with `Ramda`, since this seems like a fault of their implementation so it shouldn't desireable to keep it. If dropping backwards-compatibility isn't an option, we could instead provide both the backwards-compatible version, which would use their old names, and the improved version using new names/on a different repository (e.g., on `Rambdax`)/by toggling some build-options?

**Comment by selfrefactor** [comment]
I intend to make a breaking change. What I need is discussion, if this suggestion has grounds, so I thank you for your input.

**Comment by selfrefactor** [comment]
I am closing this issue, as there is no enough traction for this to be applied to Rambda.
