### ISSUE TITLE
Rambda 8.4.0 - Type 'K' cannot be used to index type 'Args'

### ISSUE THREAD

**Issue by memark** [selfrefactor/rambda#705]
### Issue
When upgrading from Rambda 8.3.0 to 8.4.0 on a medium-sized code base using Node 18.16.1, Yarn 1.22.19, React 18.2.0, TypeScript 5.2.2 the following error appears:

```
❯ yarn tsc
yarn run v1.22.19
$ <redacted>/node_modules/.bin/tsc
node_modules/rambda/index.d.ts:1106:46 - error TS2536: Type 'K' cannot be used to index type 'Args'.

1106 ): Args extends [...{[K in keyof ArgsGiven]: Args[K]}, ...infer ArgsRemaining]
                                                  ~~~~~~~

node_modules/rambda/index.d.ts:1119:46 - error TS2536: Type 'K' cannot be used to index type 'Args'.

1119 ): Args extends [...{[K in keyof ArgsGiven]: Args[K]}, ...infer ArgsRemaining]
                                                  ~~~~~~~


Found 2 errors in the same file, starting at: node_modules/rambda/index.d.ts:1106

error Command failed with exit code 2.
info Visit https://yarnpkg.com/en/docs/cli/run for documentation about this command.
```

### Rambda version
8.4.0

### Node.js version
18.16.1

I can try to produce an MRE later on if that would help.

**Comment by selfrefactor** [comment]
Can you share also TS version as in this case, it is important?

**Comment by memark** [comment]
Of course, it's 5.2.2. (It's actually in the OP as well.)

**Comment by teobmg** [comment]
Same problem here, TS version 5.1.6

Here is my tsconfig:
```
{
  "compilerOptions": {
    "module": "commonjs",
    "esModuleInterop": true,
    "allowJs": true,
    "allowSyntheticDefaultImports": true,
    "target": "es2017",
    "noImplicitAny": true,
    "moduleResolution": "node16",
    "resolveJsonModule": true,
    "sourceMap": true,
    "outDir": "dist"
  },
  "include": [
    "src/**/*"
  ]
}
```

**Comment by memark** [comment]
Good idea, here's my tsconfig as well

```
{
  "compilerOptions": {
    "target": "ESNext",
    "useDefineForClassFields": true,
    "lib": ["DOM", "DOM.Iterable", "ESNext"],
    "allowJs": false,
    "skipLibCheck": false,
    "esModuleInterop": false,
    "allowSyntheticDefaultImports": true,
    "strict": true,
    "forceConsistentCasingInFileNames": true,
    "module": "ESNext",
    "moduleResolution": "Node",
    "resolveJsonModule": true,
    "isolatedModules": true,
    "noEmit": true,
    "jsx": "react-jsx",
    "baseUrl": "./",
    "paths": {
      "~/*": ["src/*"]
    }
  },
  "include": ["./src"],
  "types": ["googlemaps"]
}
```

**Comment by Retro64** [comment]
Can also confirm this error on TS 5.22

**Comment by selfrefactor** [comment]
Closing this as new version `8.5.0` is fixing this. Let me know if that is not the case.

**Comment by memark** [comment]
Confirmed, `8.5.0` doesn't have this problem for me. Well done! @selfrefactor
